services:
  postgres:
    container_name: nest-godash
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nestdash
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres